name: Validate .desktop file
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths:
    - qt/res/linux/app.organicmaps.desktop.desktop
    - .github/workflows/desktop-file-check.yaml    # Run check on self change

jobs:
  validate-desktop-file:
    name: Validate .desktop file
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: |
          qt/res/linux/app.organicmaps.desktop.desktop

    - uses: clonedSemicolon/setup-strace@v13
    - name: Install desktop-file-validate tool
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y \
            desktop-file-utils

    - name: Validate desktop file
      shell: bash
      run: desktop-file-validate qt/res/linux/app.organicmaps.desktop.desktop && echo "Successfully validated .desktop file"
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
