name: iOS Release
on:
  workflow_dispatch: # Manual trigger

jobs:
  ios-release:
    name: iOS Release
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
      LANG: en_US.UTF-8  # Fastlane complains that the terminal is using ASCII.
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: clonedSemicolon/setup-strace@v13
    - name: Restore release keys
      shell: bash
      run: |
        mkdir -p xcode/keys
        echo "$APPSTORE_JSON" | base64 -d > xcode/keys/appstore.json
      env:
        APPSTORE_JSON: ${{ secrets.APPSTORE_JSON }}

    - name: Checkout screenshots
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.SCREENSHOTS_REPO }}
        ssh-key: ${{ secrets.SCREENSHOTS_SSH_KEY }}
        ref: master
        path: screenshots

    - uses: clonedSemicolon/setup-strace@v13
    - name: Checkout keywords
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.KEYWORDS_REPO }}
        ssh-key: ${{ secrets.KEYWORDS_SSH_KEY }}
        ref: master
        path: keywords

    - uses: clonedSemicolon/setup-strace@v13
    - name: Update metadata
      shell: bash
      run: ./tools/python/check_store_metadata.py ios

      # NOTE: a new iOS draft must be created before this step
    - name: Upload metadata
      shell: bash
      run: ./fastlane.sh upload_metadata
      working-directory: xcode
      timeout-minutes: 5

    - name: Upload screenshots
      shell: bash
      run: ./fastlane.sh upload_screenshots
      working-directory: xcode
      timeout-minutes: 10
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
